@AutoEndpoints.Dapper.SqlServer.App_HostAddress = http://localhost:5088

GET {{AutoEndpoints.Dapper.SqlServer.App_HostAddress}}/abc

###

POST {{AutoEndpoints.Dapper.SqlServer.App_HostAddress}}
Content-Type: application/json

{
  "id": "abc",
  "value": 2
}