@AutoEndpoints.Cosmos.App_HostAddress = http://localhost:5038

GET {{AutoEndpoints.Cosmos.App_HostAddress}}/abc/1

###

POST {{AutoEndpoints.Cosmos.App_HostAddress}}/abc/1
Content-Type: application/json

{
  "id": "1",
  "partition": "abc",
  "value": 2
}