services:
  
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    mem_limit: "256m"

  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator  
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
    mem_limit: "1g"
  
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=a123456789!
    mem_limit: "2g"