on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Build
        run: dotnet build ./src/AutoEndpoints.sln

      - name: Format
        run: dotnet format --verify-no-changes --no-restore ./src/AutoEndpoints.sln